language: python
python:
  - "3.6"      # current default Python on Travis CI

sudo: 'required'
services:
  - 'docker'

before_install:
  - chmod +x main.sh
  - '.travis/main.sh'

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test

after_success:
    - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
        make push-image ;
      fi

notifications:
    email: false