language: python
python:
  - "3.6"      # current default Python on Travis CI
sudo: 'required'
services:
  - 'docker'

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python manage.py test

# push docker image on build success
after_success:
- DOCKER_TAG=$TRAVIS_BRANCH
- DOCKER_REPO=saipranavk/mynk
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build . -t mynk
- if [ $TRAVIS_BRANCH == "master"]; then
  docker tag mynk:latest ${DOCKER_REPO}:latest;
  else
  docker tag mynk:latest ${DOCKER_REPO}:${DOCKER_TAG};
  fi
- docker push ${DOCKER_REPO}:${DOCKER_TAG}

notifications:
    email: false