# Generated by Django 3.1.1 on 2020-10-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_log', '0003_expenselog_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselog',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
