# Generated by Django 3.1.1 on 2020-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_savings',
            field=models.PositiveIntegerField(default=0, help_text='SEK/month', verbose_name='Monthly Savings'),
        ),
    ]
