# Generated by Django 3.1.1 on 2020-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200930_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='this_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
