# Generated by Django 3.1.1 on 2020-10-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_this_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='this_month',
            field=models.FloatField(default=0),
        ),
    ]
