# Generated by Django 3.1.1 on 2020-10-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysnap',
            name='category',
            field=models.CharField(max_length=128),
        ),
    ]
