# Generated by Django 3.1.1 on 2020-10-29 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20201022_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysnap',
            name='spent',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_exp',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
